server:
  port: 8081

management:
  server:
    port: 8091
  endpoints:
    enable-by-default: false
  endpoint:
    health:
      enables: true
      probes:
        enabled: true

app:
  cache:
    size: 365
  rest:
    api:
      prefix: /api
cbr:
  url: "https://cbr.ru/scripts/xml_daily.asp"